### PR TITLE
from boolean to two constructors

### PR DESCRIPTION
**Pull request by diasdavid**
@dignifiedquire there you go 

solves - https://github.com/diasdavid/js-multistream/issues/15

### CODE REVIEW

**Comment by dignifiedquire** [comment]
LGTM as soon as CI is happy

**Comment by dignifiedquire** [comment]
thank you :)

**Comment by dignifiedquire** [comment]
I just realised, this is missing updating the readme I think

**Comment by diasdavid** [comment]
updated the readme as well :) thank you for catching that (so much code churn ahah)

**Pull request merged**
